### ISSUE TITLE
Merge gar1t/Emysql-merged changes

### ISSUE THREAD

**Issue by gar1t** [Eonblast/Emysql#109]
To create a clean commit history I created a new repo and hand-merged the enhancements from gar1t/Emysql. The merged repo is here:

https://github.com/gar1t/Emysql-merged

The changes are in a single commit at the head:

https://github.com/gar1t/Emysql-merged/commit/f050405b36845f7149bbbd9f82d80a6f513a4ce8

It should merge cleanly. Unfortunately github's magical pull request feature only supports PRs from known forks (as it seems to me, maybe I'm missing something). Otherwise, I'd just create a PR.

**Comment by jlouis** [comment]
This one has been merged now, thanks!
