### ISSUE TITLE
Name Collision for "connection" record

### ISSUE THREAD

**Issue by lsowen** [Eonblast/Emysql#11]
I am utilizing Emysql in a project which also uses RabbitMQ.  Both libraries have records called connection, so to solve the issue, it would be helpful if the connection record was renamed to something more specific to the project, such as emysql_connection.

I can supply a patch if need be.

Thanks!

**Comment by Eonblast** [comment]
Appreciated, yes.

**Comment by Eonblast** [comment]
Closed with pull #12.
