### ISSUE TITLE
Add type specs to the records in `emysql.hrl`

### ISSUE THREAD

**Issue by jlouis** [Eonblast/Emysql#125]
If the record in `emysql.hrl` had type specs we would gain a lot of extra knowledge
- The dialyzer would be much stronger at getting stuff right
- The it would easier to know what to fill in there
- Documenting this will uncover latent style errors in the code base

**Comment by jlouis** [comment]
It seems my hunch was correct. This uncovered funny things in the code base :)

**Comment by jkingsbery** [comment]
There still are the `greeting` and `field` records. I'm working on adding types for those as well.

**Comment by jlouis** [comment]
We'll let this one be open for now then. Say when it can be closed.

**Comment by jkingsbery** [comment]
Just submitted a pull request that should finish this one.

**Comment by jlouis** [comment]
Rawr :)
