### ISSUE TITLE
proplists:get_value() not working with emysql_util:as_proplist()  

### ISSUE THREAD

**Issue by dnldd** [Eonblast/Emysql#136]
using as proplist:get_value() on emysql_util:as_proplist() return type fails even when the correct key is passed.

**Comment by jlouis** [comment]
Hi,

What is failing more specifically? Could you provide a small example of a return value (`#result_packet {}`) which has been shoved through `emysql:as_proplist/1` ? We have had some cleanup to that code path. If it doesn't work like it should, I want to use your example as the basis for a test case so it can be weeded out going forward.

**Comment by dnldd** [comment]
I can't reproduce this currently, pretty sure this was happening however. Recompiling emysql seems to have solved the problem. I was using the code snippet below:

```
get_service(Name) ->
    emysql:prepare(get_service, 
        <<"SELECT `service`.`id` FROM `service` WHERE `service`.`name`= ? AND online=1">>),
    ResultPacket = emysql:execute(user_pool, get_service, [Name]),
    ResultType = is_record(ResultPacket, result_packet),

    case ResultType of
        true -> 
            List = emysql:as_proplist(ResultPacket),
            proplists:get_value(<<"id">>, List);
        false -> 
            lager:error("get_service() failed, returned -> ~p", [ResultPacket]),    
            ResultPacket
    end
.
```

will dump the output here if it happens again. thanks

**Comment by jlouis** [comment]
Closing for now.
