### ISSUE TITLE
How to get procedure Result??

### ISSUE THREAD

**Issue by michael8335** [Eonblast/Emysql#138]
hi
this is my mysql procedure:
create procedure xxxxx.add_site_7137548(out n int) 
    begin 
        declare error integer default 0;
        declare continue handler for sqlexception set error=1;
        start transaction ;
        insert into ref_site_status(user_id,sid,name,domain,industry,defaultua,status,datetime,defaultwidth,defaultdelay,sitetype,defaultpage,timezone,timezonestring,date,dc_keep_days,hm_keep_days,website_type,primary_domain) values(563,'12e18e19','datatest11','datatest11.xxx.com','','Mozilla/5.0 (Linux; U; Android 2.2) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',0,1397118432664,'320','0',3,'','GMT +09:00','(GMT +09:00) Japan',now(),93,93,'11','http://xxx.com'); 
        if error = 1 then rollback;
        else commit; 
        end if; 
        select @error;
    end

call xxxxx.add_site_7137548(@n) 
my question is how can i get the error value by using  emysql:execute(PId,Sql),i need to know if the procedure rollback or not
 thank you

**Comment by jlouis** [comment]
The MySQL driver will respond appropriately when you `CALL xxxxx.add_site_7137548(?)`. It will repsond with `[#result_packet{}, #ok_packet{}]` for this and the result should contain the contents of the select on the error.

We mostly just reflect what MySQL returns back, on coding is done on the results. If you think this is insane, you should not be using MySQL (I think it is insane :)
