### ISSUE TITLE
record "connection" name clash with amqp_client record

### ISSUE THREAD

**Issue by emacstheviking** [Eonblast/Emysql#15]
I don't know who is right or wrong, but I thought that it was "best practice" to prefix all record names with the module name to avoid clashes because Erlang doesn't have name spaces for these things, yet?.

I have a situation where I am using Emysql and the amqp_client in the same module and guess what, they are both trying to define a record called "connection":

./lib/erlang/lib/emysql-0.2/include/emysql.hrl:30:-record(connection, ...
./lib/erlang/lib/rabbit_common-2.7.0/include/rabbit.hrl:30:-record(connection, {protocol, user, ...

I am going to change the Emysql code and rebuild and reinstall it into my local Erlang development zone and see how I get on, I will submit patches or something unless you beat me to it first!  I fancy my chances of tinkering with Emyswl and not breaking it as higher than fiddling with the amqp_client at the moment.

All the best!
Sean Charles.

**_UPDATE**_\* I have realised that his has been fixed  and I have checked out this version:

Author: Logan Owen logan.owen@fellonmccord.com
Date:   Wed Aug 31 19:13:30 2011 -0400

```
avoid name collision with RabbitMQ for the connection record by renaming it to emysql_connection
```

BUT IT STILL STANDS that all of the records should be prefixed with "emysql_" as sooner or later the problem is bound to come up again. For now I will use this version and be happy. Is it worth me finding the time to modify all the records for you ?

**Comment by hdiedrich** [comment]
"Is it worth me finding the time to modify all the records for you?"

Thanks for the offer! Yes, please go ahead, if you send me a pull request, I'll be happy to merge it into main.

There were some minor changes in the mean time, please pull before editing. Also, Common Tests were added. You can run them using "make test". It may help making sure nothing broke when doing the renaming. 

Please let me know, which records you touched and I will go through it and double check in the end.

Again, how come you had an older version, missing the RabbitMQ fix? Simply checked out so long ago, before the update?

Thanks,
Henning

**Comment by emacstheviking** [comment]
Merry Christmas Henning!

I have had a busy week but I have found the time to make all of the
records in the Emysql driver start with "_emysql" and it bulds and runs
fine on my project.

So... how do I get it back into the system with you? I've pulled many a
project from GitHub but never put anything back, shame on me I know but
here comes the first one!

:)
All the best,
Sean.

**Comment by hdiedrich** [comment]
Hi Sean!

Thanks so much!

You would open a "Pull Request", using the button at the top.

http://help.github.com/send-pull-requests/

Did you really make it start with an underscore?

Have a Merry Christmas!
Henning

**Comment by emacstheviking** [comment]
Henning,

I forked the project and put my changes bacK

commit e01e2fdb79d25684eda6e1f8353110d283529470
Author: Sean Charles sean@objitsu.com
Date:   Sat Dec 24 14:39:14 2011 +0000

```
 Modified comment to point out my changes to record definitions.
```

commit b0b6bd2729b6afe756d081709e8e45167b75f5b1
Author: Sean Charles sean@objitsu.com
Date:   Sat Dec 24 14:35:49 2011 +0000

```
 Renamed all record definitions so that they begin with "emysql_" to
```

However, nothing seems to be showing up on my forked copy... I've neve 
rused GitHub before so it's probably all my fault... can you tell me 
what I have to do to finish it? When I followed you instructions to send 
a pull request it told me that my copy and the master were already up to 
date so I am assuming it hasn't yet seen my changes I've pushed back?

Cheers,
Sean.

**Comment by jlouis** [comment]
This has been fixed, at least for the `connection` record. There is another issue for the remaining records at #65
