### ISSUE TITLE
There is some function changed in R17 like crypto

### ISSUE THREAD

**Issue by ronalfei** [Eonblast/Emysql#156]
emysql_auth.erl:156: Warning: crypto:sha/1 is deprecated and will be removed in in a future release; use crypto:hash/2
emysql_auth.erl:157: Warning: crypto:sha/1 is deprecated and will be removed in in a future release; use crypto:hash/2
emysql_auth.erl:158: Warning: crypto:sha_final/1 is deprecated and will be removed in in a future release; use crypto:hash_final/1
emysql_auth.erl:159: Warning: crypto:sha_update/2 is deprecated and will be removed in in a future release; use crypto:hash_update/2
emysql_auth.erl:160: Warning: crypto:sha_init/0 is deprecated and will be removed in in a future release; use crypto:hash_init/1
emysql_auth.erl:160: Warning: crypto:sha_update/2 is deprecated and will be removed in in a future release; use crypto:hash_update/2

**Comment by ddosia** [comment]
Have you tried latest `master` branch? I believe this was resolved with df6ce595b82428372da826e103eb2341d4674894 trick by generating different `include/crypto_compat.hrl` at compile time.

**Comment by ronalfei** [comment]
sorry, that caused by my openssl nif. so that works ok  when I reinstall openssl and recompile otp.
thank you, close it!
