### ISSUE TITLE
Maintain Active Redundant DB connection (switch from Active MySQL DB to Redundant MySQL DB instance)

### ISSUE THREAD

**Issue by alawatta** [Eonblast/Emysql#165]
Hi,
Pls let me know how to implement logic using emysql to switch from Active MySQL DB to Redundant MySQL DB instance.
My Erlang program run in server A. My MySQL DB run on server B & Server C. (master-master) I need to add 2 database to connection pool. 
if one db down (Say Server B) , then program need to refer  Server C connection. automatically through emysql.That is my requirement.
Br,
Shehan

**Comment by jlouis** [comment]
There is no support in emysql for this.

What you can do is the following implementation:
1. Create two pools, one for each MySQL server.
2. Protect both pools by a "circuit breaker" application.
3. If the primary pool breaks it's circuit, start using the other pool.
4. If both circuits are broken, report an error to the caller.
