### ISSUE TITLE
While Creating .beam files in windows found Error 

### ISSUE THREAD

**Issue by bhattnishant** [Eonblast/Emysql#18]
Hello

In windows ,i create manually .beam files using this command

erlc -I includes/ejabberd/include emysql_conn.erl

Which command i found from http://www.ejabberd.im/ejabberd-modules

All ".beam" files are created successfully except this two files...

emysql_conn.erl
emysql_util.erl

try with this command 

erlc -I includes/ejabberd/include emysql_conn.erl
Error:
C:/Program Files/ejabberd-2.1.9/bin/emysql_conn.erl:55: function atom_to_binary/2 undefined
C:/Program Files/ejabberd-2.1.9/bin/emysql_conn.erl:79: function atom_to_binary/2 undefined

erlc -I includes/ejabberd/include emysql_conn.erl
Error:
C:/Program Files/ejabberd-2.1.9/bin/emysql_util.erl:57: function binary_to_atom/2 undefined

Please advice me how to create .beam files for ejabberd in windows system...

Thanks
Nishant Bhatt

**Comment by Eonblast** [comment]
Hi Nishant!

ejabberd does not use this Emysql package but uses a version from Yxa that uses the same prefix 'emysql'. 

See https://support.process-one.net/doc/display/MESSENGER/Using+ejabberd+with+MySQL+native+driver
and here https://github.com/Eonblast/Emysql#History

Regardless, I suspect your Erlang version is not meeting the ejabberd requirements and upgrading Erlang could help. The functions you are missing where built into Erlang some years ago.

Best,
Henning

**Comment by nishant-zz** [comment]
Hello Henning

yes i understand that, However i want to store chat in mysql database i am trying to implement this https://github.com/candy-chat/mod_log_chat_mysql5

i tried in ejabbered newer beta version there i can create .beam files successfully however chat not stored in db.

Could you tell me what actually i change and it working on my system?

what i change in YXa with mod_log_chat_mysql5 module?

Please help me!

Thanks
Nishant

**Comment by hdiedrich** [comment]
Hi Nishant,

Sure, I think you should start by solving why atom_to_binary/2 is not available.

This function is available in the current standard Erlang distribution. http://www.erlang.org/doc/man/erlang.html#atom_to_binary-2 It was not available in older Erlang distributions.

You may want to try upgrading your Erlang install.

Best,
Henning

**Comment by nishant-zz** [comment]
Hello Henning

yes, in erlang newer version it compile successfully however chat not stored in db :(

Please look inside if you can, also not get any kind of errors too :|

i tried inside ejabbered3 beta which is with newer version of erlang..

Please Help!

Thanks
Nishant

**Comment by Eonblast** [comment]
Not sure what I can do to help you Nishant, this is also not really the place.

Are you sure mod_log_chat_mysql5 works with ejabbered3? Erlang and ejabberd are really two distinct things. You should probably upgrade Erlang on your system, maybe using ejabbered3, and then use that Erlang to run ejabberd2.

But I guess Google, the Erlang mailing list or contacting candy-chat, who maintains mod_log_chat_mysql5, would be more useful for you.
