### ISSUE TITLE
after a long time idle ,the connection lost

### ISSUE THREAD

**Issue by helloyan** [Eonblast/Emysql#28]
i found  the sql returns {failed_to_recv_packet_header,closed} after a long time idle,would you add the feature to keep alive?

**Comment by Eonblast** [comment]
Thanks for reporting, please tell me more. 

How long is long?
Does the MySQL server close the connection?
Is the same happening if you simply shut the server down?

**Comment by helloyan** [comment]
about 3/4 days,
mysql close the connection
if i restart the application,everyting is ok

**Comment by Eonblast** [comment]
If you simply restart the mysql server during a time when there are no requests running, does it produce the same errors? My thinking is that the restart should also close the connections.

When you re-do the same request after the error I guess then it works ok, right? It's only the first one that fails? In other words: the restart of your application is also solving it I understand, but simply re-doing it (and thus not restarting the entire Emysql app) might also solve it?

Thanks,
Henning

**Comment by helloyan** [comment]
maybe  
now i use a timer to keeplive

**Comment by Eonblast** [comment]
Let me know some more details to see if we can make Emysql better from your experience.

Thanks,
Henning

**Comment by helloyan** [comment]
i think you can connect mysql for 3 or 4 day for idle, it may reduce the issuse

**Comment by Eonblast** [comment]
Please share some details, I'd like to use them to improve Emysql base upon them.

Thanks,
Henning

**Comment by jameszhou** [comment]
the details is i shared before,what other details do you want?

**Comment by Eonblast** [comment]
When you received the errors, did simply re-trying work?

**Comment by jameszhou** [comment]
no,it does lost connection

**Comment by Eonblast** [comment]
Well, let's simply shelve this conversation. Still, thanks for reporting!

**Comment by gulige** [comment]
For the line 573 in emysql.erl:
573     {'DOWN', Mref, process, Pid, {_, closed}} ->
I doubt it could cover all tcp errors especially gen_tcp:send/2 in emysql_tcp.erl
Please see the description of the returns of gen_tcp:send/2 for reference.
I think all the other tcp error cases should be matched in this case branch for better experience.
