### ISSUE TITLE
Inefficient set_params implementation for prepared statements

### ISSUE THREAD

**Issue by thijsterlouw** [Eonblast/Emysql#29]
I noticed that emysql_conn:set_params/4 in
https://github.com/Eonblast/Emysql/blob/master/src/emysql_conn.erl#L237 is a bit inefficient. For each parameter that is bound, it will do a emysql_tcp:send_and_recv_packet/3 . 

emysql_tcp:send_and_recv_packet in https://github.com/Eonblast/Emysql/blob/master/src/emysql_tcp.erl#L36 already does framing (prefix a length + sequence number). So I think the protocol allows us to send all the parameters at once, or at least without the need to wait for all replies and send sequentially.

I will do some tests and if it turns out to indeed be possible and faster to send these differently (either one large sync call, or many async calls), then I will propose a change.

**Comment by thijsterlouw** [comment]
This issue is just to keep track of a discussion we had in Stockholm at the Erlang User Conference in 2012 :)

**Comment by hdiedrich** [comment]
Yes, maybe you could also check on the wire(shark) level if for some reason this might be automatically nagled on the TCP/IP layer?

As I said I believe there might be a huge performance gain in this. Thanks again for bringing it up!

Henning

**Comment by thijsterlouw** [comment]
I think Nagles algorithm doesn't help (might even hurt) since we are waiting for the receive as well. If it was only sending (async) Nagle would help.

**Comment by hdiedrich** [comment]
Yes.

**Comment by hdiedrich** [comment]
Thijs, you want to propose a pull request for this?

Thanks,
Henning

**Comment by thijsterlouw** [comment]
Hi Henning, totally forgot about this! I will do it, but will probably take a couple of days (eg. the weekend :))

**Comment by Eonblast** [comment]
Hi Thijs!

I found a fork where this has been addressed. Maybe you want to check it out and test it?

https://github.com/opscode/Emysql/commit/f0cff286661bc8cc3cd9526e909477cf98016bfe

This whole fork looks good.

Thanks a lot!
Henning

**Comment by thijsterlouw** [comment]
This is exactly what I mean and it apparently indeed gave a nice performance improvement. I suggest to merge this back into the eonblast/emysql. We can then close this issue.

**Comment by hdiedrich** [comment]
Fixed w/ #62. See you at EUC, Thijs?

**Comment by thijsterlouw** [comment]
yes, I will be there again this year! :)
