### ISSUE TITLE
remove io:format when using latin1 encoding

### ISSUE THREAD

**Issue by TheSquad** [Eonblast/Emysql#32]
Hi, would it be possible to remove in the repository the io:format used to check if encoding has been done correctly... I can affirm that it does work correctly without any glitch, for using it a certain time now.

The code is in the emysql_util.erl file at line 196 and 198...

Unless there is a good reason to keep it in here, in this case I'll keep edit the file by hand, thanks !

**Comment by Eonblast** [comment]
Fixed, thanks a lot!

**Comment by TheSquad** [comment]
No, thank you !
