### ISSUE TITLE
[proposal] time_zone support per connection pool

### ISSUE THREAD

**Issue by motiejus** [Eonblast/Emysql#41]
Hi,

Proposal for the new functionality:
1. add `timezone` field to `#pool{}`.
2. create `emysql_conn:set_timezone/2` (very similar to `emysql_conn:set_database/2`).
3. add backwards-compatible `emysql:add_pool/9`.

If you think that current `emysql:add_pool/8` is becoming too big, I can refactor it to something like:

```
add_pool(PoolId, Size, User, Password, Host, Port, Opts)
Opts = [{key(), value()}].
key() = database | encoding | time_zone.
```

And analogously `#pool{}`.

Note: this would be backwards-compatible (but not intuitive):

```
add_pool(PoolId, Size, User, Password, Host, Port, Opts)
add_pool(PoolId, Size, User, Password, Host, Port, Database, Encoding)
```

And, if we agree on that, after transition period `emysql_conn:add_pool/8` should be removed.

Let me know which one you prefer.

**Comment by hdiedrich** [comment]
Hi, see my response to your comprehensive pull request #43.

**Comment by motiejus** [comment]
This is possible since 437940905ec6aa199ea31948de362dda6336b1e6. Closing.
