### ISSUE TITLE
load local infile not allowed

### ISSUE THREAD

**Issue by qingliangcn** [Eonblast/Emysql#44]
the sql is :
LOAD DATA low_priority local INFILE '/data/logs/behavior_intime/4399_41/t_log_role_create/2012_10_31/13/log.t_log_role_create.8.2012_10_31_13_14.log' INTO TABLE 4399_xlfc_41.t_log_role_create (`pid`     ,`role_id`, `role_name`       ,`account_name`    ,`create_time`     ,`sex`     ,`faction_id`, `category`);

get this error:
{error_packet,1,1148,<<"42000">>,
              "The used command is not allowed with this MySQL version"}

mysql version is 5.5.18

i compiled mysql with  --enable-local-infile

**Comment by qingliangcn** [comment]
i have fixed like this:
Caps = ?LONG_PASSWORD bor ?CLIENT_LOCAL_FILE bor ?LONG_FLAG bor ?TRANSACTIONS bor
        ?CLIENT_MULTI_STATEMENTS bor ?CLIENT_MULTI_RESULTS bor
        ?PROTOCOL_41 bor ?SECURE_CONNECTION bor DBCaps,

**Comment by qingliangcn** [comment]
-define(CLIENT_LOCAL_FILE, 128).

**Comment by qingliangcn** [comment]
here is my fix.
https://github.com/qingliangcn/Emysql/commit/a02fb1d032536aeabc44d62aa57bf11c9d7c9979

**Comment by hdiedrich** [comment]
Hi Liang,

looks good, thanks for sharing! Would you care to open a pull request?

Thanks,
Henning

**Comment by qingliangcn** [comment]
OK,done

**Comment by Eonblast** [comment]
Its merged, thanks a lot!

**Comment by jlouis** [comment]
Since this has been merged, can we close the issue?

**Comment by hdiedrich** [comment]
Yes, I was waiting for reports on whether it worked. The wait may be long enough now, closing.
