### ISSUE TITLE
encode(Val, binary, _) when is_float(Val) returns list instead of binary

### ISSUE THREAD

**Issue by IvanYuilop** [Eonblast/Emysql#47]
The function in line 224 of emysql_util.erl returns a list when it should return a binary. This bug makes line 240 of emysql_conn.erl to fail when updating a table with a float value:

(energyservice_node@127.0.0.1)12> emysql:execute(api_pool, update_activity_r, [0, 190.5, 293209]).
16:43:36.441 [error] Lager event handler error_logger_lager_h exited with reason {'EXIT',{function_clause,[{lager,log,[error,emulator,["Error in process <0.314.0> on node 'energyservice_node@127.0.0.1' with exit value: {badarg,[{erlang,byte_size,[\"190.5\"],[]},{emysql_conn,set_params,4,[{file,\"src/emysql_conn.erl\"},{line,240}]},{emysql_conn,execute,3,[{file,\"src/emysql_conn.erl\"},{line,82}]},{emysql,'-monitor_work/3-fun-0-',4,[{file,\"src/emysql... \n","\n"]],[{file,"src/lager.erl"},{line,86}]},{error_logger_lager_h,handle_event,2,[{file,"src/error_logger_lager_h.erl"},...]},...]}}
16:43:36.504 [debug] Lager installed handler error_logger_lager_h into error_logger
*\* exception exit: {{badarg,[{erlang,byte_size,["190.5"],[]},
                             {emysql_conn,set_params,4,
                                          [{file,"src/emysql_conn.erl"},{line,240}]},
                             {emysql_conn,execute,3,
                                          [{file,"src/emysql_conn.erl"},{line,82}]},
                             {emysql,'-monitor_work/3-fun-0-',4,
                                     [{file,"src/emysql.erl"},{line,567}]}]},
                    {}}
     in function  emysql:monitor_work/3 (src/emysql.erl, line 592)

This bug can be fixed by simply changing line 226 of emysql_util.erl to:

list_to_binary(Res);

AFAIK this bug was first spotted by valinurovam:

https://github.com/Eonblast/Emysql/pull/39

**Comment by jeremyong** [comment]
+1 Not being able to handle floats in prepared statements is somewhat of a nuisance.

**Comment by IvanYuilop** [comment]
Hopefully fixed in #59

**Comment by jlouis** [comment]
Fixed with pull request #59, and in order to make things easier on us, let us further discuss the issue in that ticket number.
