### ISSUE TITLE
Running Make Throws Compile-time Errors

### ISSUE THREAD

**Issue by jazzdan** [Eonblast/Emysql#5]
Following the included readme file leads to several error messages. When I ran the make command in the Emysql directory, the following error occurred:

$ make
mkdir -p ebin
(cd src;make)
make[1]: Entering directory `/home/dan/fire/Emysql/src'
erlc -W -I ../include  +debug_info -o ../ebin emysql_app.erl
erlc -W -I ../include  +debug_info -o ../ebin emysql_auth.erl
erlc -W -I ../include  +debug_info -o ../ebin emysql_conn.erl
./emysql_conn.erl:206: undefined macro 'SERVER_MORE_RESULTS_EXISTS'
./emysql_conn.erl:29: function hstate/1 undefined
make[1]: *** [../ebin/emysql_conn.beam] Error 1
make[1]: Leaving directory`/home/dan/fire/Emysql/src'
make: **\* [all] Error 2

This happens under an unprivileged account and the root account. The following are the particulars of my environment:

$ uname -a
Arch Linux 2.6.36-ARCH #1 SMP PREEMPT Mon Jan 24 18:41:03 CET 2011 x86_64 AMD Phenom(tm) II X6 1055T Processor AuthenticAMD GNU/Linux

$ pacman -Q erlang
erlang R14B-1

Although I have not tested this thoroughly to verify that there is no loss of funtionality, commenting out line 206 in the emysql_conn.erl file so it reads like this:

%%++ case (State band ?SERVER_MORE_RESULTS_EXISTS) of 0 -> ""; _-> "MORE_RESULTS_EXISTS " end    

Allowed the make to complete successfully. I will post back if any loss of functionality occurs.

**Comment by Eonblast** [comment]
Thanks, should be fixed with 0eef08bc533e736ef1a1. A typo in the define. Wrong: S in the end. Likely inherited from MySQL headers. Culprit was a too lenient makefile include, support/makefile.mk, that allowed include/emysql.hrl to get out of sync with the source without rebuilding.
