### ISSUE TITLE
Document LOAD DATA INFILE

### ISSUE THREAD

**Issue by Eonblast** [Eonblast/Emysql#52]
LOAD DATA low_priority local INFILE '/data/logs/behavior_intime/4399_41/t_log_role_create/2012_10_31/13/log.t_log_role_create.8.2012_10_31_13_14.log' INTO TABLE 4399_xlfc_41.t_log_role_create (pid ,role_id, role_name ,account_name ,create_time ,sex ,faction_id, category);

**Comment by jlouis** [comment]
Isn't this solved by #44 as well?

**Comment by hdiedrich** [comment]
This issue was about writing documentation about #44. I am doing that right now. Unless you feel like it?

**Comment by jlouis** [comment]
Not really. I am more inclined to look into a test case for adding binary data to BLOB columns while running in utf8 encoding mode :)

**Comment by hdiedrich** [comment]
Sounds great! In the mean time, this is addressed, incl. samples. Though lacking a test suite at this point.
