### ISSUE TITLE
Proposal: Remove Strings As Lists and Locale Encoding

### ISSUE THREAD

**Issue by hdiedrich** [Eonblast/Emysql#58]
From csrl:
As a general comment - unrelated to this specific pull request, I'd love to see all of the string as list and locale encoding code removed from the project, and have it work only on binaries. Push the encoding to the application layer where it belongs. With the encoding in place in the emysql layer, one looses all of the benefits of iolists.

**Comment by jlouis** [comment]
I agree, Robert Virding agrees, I think @opscode agrees too. The programmer needs to be in charge of what kind of data he is sending to the database. To the driver, this has to be binary data only.

**Comment by jlouis** [comment]
This proposal has now been implemented in `master`
