### ISSUE TITLE
crash while connecting - emysql_auth - badmatch

### ISSUE THREAD

**Issue by mme** [Eonblast/Emysql#6]
I am getting an error trying to connect, for example:
$ erlc hello.erl
$ erl -pa ./ebin -s hello run -s init stop -noshell

{"init terminating in do_boot",{{badmatch,{"lN\"+]sK_x_S",<<21 bytes>>}},[{emysql_auth,recv_greeting,1},
{emysql_auth,do_handshake,3},
{emysql_conn,open_connection,1},{emysql_conn,open_connections,1},
{emysql,add_pool,8},{hello,run,0},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

the demo user is set up correctly.

mac os x snow leopard
erlang version is R14A
mysql is 5.5.9

**Comment by hdiedrich** [comment]
Please retry with the head of the dev branch. 

git pull origin dev
git checkout dev

or

git clone -b dev git://github.com/Eonblast/Emysql.git emysql-dev
cd emysql-dev

then

make
erlc hello.erl
erl -pa ./ebin -s hello run -s init stop -noshell

Your server is sending the name of its preferred plugin. The newest commit to the dev should be reading that away correctly, and also appropriately act upon it.

**Comment by mme** [comment]
Works like a charm. You rock!

**Comment by Eonblast** [comment]
Now committed to master, eliminating the debug verbosity.

Thanks for your help!
Henning
