### ISSUE TITLE
Documentation for safe SQL queries

### ISSUE THREAD

**Issue by chad-simplisafe** [Eonblast/Emysql#69]
Sorry if this isn't the right place for this request, but it looks like this is the Erlang SQL driver with the best documentation so I thought I would ask:

Can you provide any documentation or suggestions for making safe SQL queries (safe from SQL injection) using this Erlang MySQL driver?  It's not entirely clear to me if the driver does some escaping by default or if every query should be run through emysql_util:encode().  Or would you recommend using another layer to prepare SQL statements (such as https://github.com/devinus/sqerl).  

I think that adding this to the documentation or samples would help make sure Erlang code using this driver is as secure as possible.

Thanks for your work on the driver and the helpful documentation.

Chad

**Comment by jlouis** [comment]
If you use prepared statements, with placeholders, then the driver currently runs your data through a quotation step by means of the `emysql_util:encode/2,3` as you suspect.

My personal opinion is that while quotation is important, it is definitely one of those things that is better to share among several drivers if possible. It is a tricky business to get right and I would much rather want things to be wrong consistently than merely wrong somewhere. You may be able to use sqerl, but I have yet to look deeply into that project.

**Comment by chad-simplisafe** [comment]
Thanks for the quick reply. Centralizing this makes sense, I'll keep investigating to see if I can find a good library.  I suspect plenty of other people must have had to deal with this.

**Comment by jlouis** [comment]
Looking at `sqlerl` it looks like it is such a library. So you may want to check out how it works internally. There is some overlap to the `emysql_util:encode/2,3` functions.

**Comment by jlouis** [comment]
I am closing this Issue since it has no real outcome or resolution. If you want something fixed, please re-open it and rename it in a way so we are not mistaken that it is work that needs to be done.
