### ISSUE TITLE
A way to make encoding truly optional

### ISSUE THREAD

**Issue by motiejus** [Eonblast/Emysql#80]
Older versions of Sphinx (pre 2.0.2 more specifically)\* do not implement "SET NAMES" command. I suggest adding an exception that, if `undefined` is passed as encoding, no command is sent for real (at the moment it tries `SET NAMES undefined`).

Would you agree with this change? It is backwards incompatible, but I really see no reason why would anyone want current behavior.

[*]: yes, we are using emysql for talking to Sphinx, works great.

**Comment by jlouis** [comment]
Please provide a patch for this. I think it is viable to add it.
