### ISSUE TITLE
make test-all fails on many encoding tests

### ISSUE THREAD

**Issue by motiejus** [Eonblast/Emysql#89]
`make test-all` fails on lots of tests. Most of them because `emysql_util:quote/2` is undefined in 0.3, and a few extra errors. All tests used to work on 0.2.

@jlouis, I could fix them, but I guess you know the encoding subtleties in emysql way better than I do; it might just be necessary to remove most of the tests, so will not take a long time.

This came up while preparing emysql for CI environment.

**Comment by jlouis** [comment]
Most of the encoding stuff has been ripped out, so we can do with rather few tests in there I think. I have not yet taken a look at it, and I don't think I will get the time in a couple of days, but I really like the idea of pushing support on top of Travis CI.

**Comment by jlouis** [comment]
Ok, travis-ci support is in, but the encoding stuff has yet to be addressed. So I leave this issue open or can we close it? Do you still need something here?

**Comment by motiejus** [comment]
I see travis-ci only tests basic stuff (`basics_SUITE`, `conn_mgr_SUITE`), so encoding is still not fine though. I guess we can leave it open until someone builds up the courage to clean/fix those tests.

Unfortunately, I have no time for this now. But we should leave this open to highlight that it's a known issue.

**Comment by jlouis** [comment]
Will do. On the other hand, since there are no encoding in the driver, chances are that most of that code is dead anyway, heh.

**Comment by jlouis** [comment]
This has now been fixed. All the encoding tests were specific to encoding, so I decided to reap them all. While here, I enabled other tests which make sense to have, and I also added coverage for each SUITE. The next phase would be to coalesce the suites so we can run a single cover on the whole repository.
