### ISSUE TITLE
Clients killed when waiting for connections may leave the connections locked forever

### ISSUE THREAD

**Issue by bpuzon** [Eonblast/Emysql#93]
In the example below killing the client that is queuing for a free connection leaves that connection in an unusable state.
In our case it got exposed as our application was timeouting and killing the process talking to emysql before emysql own timeouts could kick in.

``` erlang
%% Setup
[application:start(A) || A <- [crypto, emysql]].
application:set_env(emysql, default_timeout, 20000).
emysql:add_pool(h, 1, "user", "pass", "localhost", 3306, "db", utf8).

%% Bug trigger
F1 = fun() -> emysql:execute(h, "select sleep(10);", 15000) end.
F2 = fun() -> emysql:execute(h, "select 1") end.

spawn(F1).
f(P).
P = spawn(F2).
timer:sleep(1000).
exit(P, kill).

%% This will never work again
emysql:execute(h, "select 1").
```

**Comment by jlouis** [comment]
Thank you for the error report. You are right it doesn't look good. Do you have a suggestion for how to fix it?

**Comment by bpuzon** [comment]
We're trying to monitor the clients one a connections are locked for them - will send a patch if it seems to work.
