### ISSUE TITLE
Database connection error ({failed_to_connect_to_database,emfile})

### ISSUE THREAD

**Issue by ahesanath** [Eonblast/Emysql#95]
Hi,
Following error coming when try to add pool. (This was initiated by parallel processes)
{'EXIT',{failed_to_connect_to_database,emfile}
Fllowing is the Erlang Code
case catch emysql:add_pool(ConnPoolId, 10, UName, Pw, host,Port, "test", utf8) of
ok ->

{ok, ConnPoolId};
{error, pool_already_exists} ->
already_exist;
{'EXIT',{failed_to_connect_to_database, emfile}} ->
io:fwrite("Else set_connection ~p~n",[{{failed_to_connect_to_database, emfile}, DbName, ConnPoolId}]),
catch spawn(?MODULE, update_status,["failed_to_connect_to_database"]),
error;
Else ->
catch spawn(?MODULE, update_status,["database_error"]),
io:fwrite("Else set_connection ~p~n",[{Else, DbName, ConnPoolId}]),
error
end.

Pls help to solve this issue.
Br,
Sanath

**Comment by jlouis** [comment]
The `emfile` error occurs when you have hit the system limit on open files. Note that a network socket is also a file in this case. Make sure that this is not the case for you first, since chances are that you simply opened up too many of them.

**Comment by ahesanath** [comment]
Hi,
Tx a lot for help. I also assumed that but your word help to find real
reason.
Br,
Sanath
